services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perplexica.rule=Host(`aisearch.savorcare.com`)"
      - "traefik.http.routers.perplexica.entrypoints=websecure"
      - "traefik.http.routers.perplexica.tls.certresolver=myresolver"
      - "traefik.http.routers.perplexicahttp.rule=Host(`aisearch.savorcare.com`)"
      - "traefik.http.routers.perplexicahttp.entrypoints=web"
      - "traefik.docker.network=reverse-proxy"

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
