use_default_settings: true

general:
  instance_name: 'searxng'

search:
  autocomplete: 'google'
  formats:
    - html
    - json
    
outgoing:
  # default timeout in seconds, can be override by engine
  request_timeout: 5.0
  # the maximum timeout in seconds
  max_request_timeout: 10.0
  
server:
  secret_key: 'a2fb23f1b02e6ee83875b09826990de0f6bd908b6638e8c10277d415f6ab852b' # Is overwritten by ${SEARXNG_SECRET}

engines:
  - name: wolframalpha
    disabled: false
